### ISSUE TITLE
Travis builds no longer work due to new payment model. 

### ISSUE THREAD

**Issue by DannyvdSluijs** [JsonMapper/JsonMapper#72]
**Describe the bug**
With the new approach of Travis in their payment model builds are no longer running. We should complete the step to coverage from the GitHub actions. 

**To Reproduce**
When running builds on Travis they don’t complete as there ar w no credits available. 

**Expected behavior**
The build should be complete running on GitHub actions including coverage.  

**Stacktrace**
N/A

**Environment (please complete the following information):**
 - Travis-ci.com
 
**Additional context**
N/A

**Todo:**
- [x] Remove Travis config
- [x] Replace build status badge
- [x] Update mergify config to look at GitHub Actions results
- [x] Add coveralls upload to GitHub Actions workflow
- [ ] Update protected branches config to no longer require travis but require GitHub Actions
